services:

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api-gateway/.env.production
    environment:
      NODE_ENV: production
    restart: always

  vendor-service:
    build:
      context: .
      dockerfile: apps/vendor-service/Dockerfile
    container_name: vendor-service
    ports:
      - "3001:3001"
    env_file:
      - ./apps/vendor-service/.env.production
    environment:
      NODE_ENV: production
    restart: always

  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "3002:3002"
    env_file:
      - ./apps/auth-service/.env.production
    environment:
      NODE_ENV: production
    restart: always

  contracts-service:
    build:
      context: .
      dockerfile: apps/contracts-service/Dockerfile
    container_name: contracts-service
    ports:
      - "3003:3003"
    env_file:
      - ./apps/contracts-service/.env.production
    environment:
      NODE_ENV: production
    restart: always

  postgres:
    image: postgres:16
    container_name: optima_postgres
    restart: unless-stopped

    env_file:
      - ./apps/api-gateway/.env.production

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak-postgres:
    image: postgres:16
    container_name: keycloak_postgres
    restart: unless-stopped

    env_file:
      - ./apps/auth-service/.env.production

    environment:
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      POSTGRES_DB: ${KC_DB_URL_DATABASE}

    ports:
      - "5433:5432"

    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    restart: unless-stopped

    command: start-dev

    env_file:
      - ./apps/auth-service/.env.production

    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}

      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}

      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      - keycloak-postgres

volumes:
  postgres_data:
  keycloak_postgres_data: