export enum DocumentType {
  GST_CERTIFICATE = 'GST_CERTIFICATE',
  PAN_CARD = 'PAN_CARD',
  CIN_CERTIFICATE = 'CIN_CERTIFICATE',
  BANK_STATEMENT = 'BANK_STATEMENT',
  MOA = 'MOA',
  AOA = 'AOA',
  MSME_CERTIFICATE = 'MSME_CERTIFICATE',
  CANCELLED_CHEQUE = 'CANCELLED_CHEQUE',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  OTHER = 'OTHER',
}